### PR TITLE
Fix mouse sensitivity

### LINKED ISSUE #56: Fix mouse sensitivity
## User Story
As a keyboard/mouse player, I want mouse sensitivity to be consistent despite changes in framerate, so that I can enjoy a smooth gaming experience

## Issue
The sensitivity of the camera (when controlled by a mouse) changes with the framerate, because it is being multiplied by Time.deltaTime when it does not need to be (higher frames = slower movement)

### PR DESCRIPTION
**Pull request by otherotherjosh**
## User Story
As a keyboard/mouse player, I want mouse sensitivity to be consistent despite changes in framerate, so that I can enjoy a smooth gaming experience

## Issue
The sensitivity of the camera (when controlled by a mouse) changes with the framerate, because it is being multiplied by Time.deltaTime when it does not need to be (higher frames = slower movement) (closes #56)

## Changes
Stopped multiplying delta (mouse/touch) input by deltaTime

### CODE REVIEW

**Review by lolyay270 — CHANGES_REQUESTED** [review]
## Review
This fix is really important and I am glad the solution has been found and is being fixed.

Although when I tested this fix, the mouse sensitivity was extremely high, and the controller was extremely low. This was the same with running in editor and build.

While testing I noticed that you were multiplying the sensitivity to the input values before the input type was tested, which would force the camera to have the wrong sensitivity for 1 frame.

Here's a tweak that I found worked on my PC (although I'm sure the exact values will differ for you):
``` c#
// Top level variables to swap for lookSensitivity
// Ive shown here in code what I had them set as in editor (they arent hard-coded) 
    [SerializeField] private float mouseLookSensitivity = 0.25f;
    [SerializeField] private float controllerLookSensitivity = 250f;

// Inside Update()
    Vector2 lookInput = lookAction.ReadValue<Vector2>(); //removed * lookSensitivity here
    float lookSensitivity; //moved down from top level

    if (!inputIsDelta) // only mutliply by deltaTime if not using delta input (mouse)
    { 
        lookInput *= Time.deltaTime; 
        lookSensitivity = controllerLookSensitivity; 
    }
    else // do not multiply by deltaTime when using delta input (mouse)
    { 
        lookSensitivity = mouseLookSensitivity; 
    }

    // moved to after input type changes, so it doesnt have wrong sensitivity for 1 frame
    lookInput *= lookSensitivity; 

    // rotate horizontally and vertically not changed 
```
The sensitivity issues being consistent with both editor and build is a really good sign. It means your fix is working! Just a couple tweaks and this will be perfect!

**Comment by lolyay270** [comment]
My apologies for reading the issue incorrectly and assuming that controller was part of this. 
I agree that controller sensitivity is out of scope and should be implemented with another issue and PR.
As for how it would be adjusted in the future, I jump between controller and mouse constantly, which means if there was only one slider for look sensitivity, I would be constantly changing it. I feel controller and mouse should be different and not depend on each other.

**Review by Christian-Irvine — APPROVED** [review]
Nice job fixing merge conflicts, happy to approve.

**Review by lolyay270 — APPROVED** [review]
## Re-Review
mouse sensitivity has been lowered

**Pull request merged**
