### PR TITLE
Added Controller Support

### LINKED ISSUE #133: Add controller support for GUI
## User Story
As a player who prefers controller, I would like to be able to use a controller to play the game, because that is what im used to.

## Issue
Add virtual cursor to screen when user is using a controller, to interact with the GUI.

### PR DESCRIPTION
**Pull request by otherotherjosh**
## User Story
As a player who prefers controller, I would like to be able to use a controller to play the game, because that is what im used to.

## Issue
Add virtual cursor to screen when user is using a controller, to interact with the GUI. (closes #133)

## Changes
- Disabled tab-style navigation (using directional keys to select next/previous UI elements)
- Added InputDeviceManager which invokes an event when a change in input device is detected
- Added a virtual cursor that is in use when the player is using a controller
- Added button bind to skip tutorial

### CODE REVIEW

**Comment by otherotherjosh** [comment]
## Review Request
The minimum viable product is done!! A couple of things that aren't entirely desirable:
- resolution is now forced at full HD (1920x1080) because the virtual cursor 
- tab style navigation is unanimously considered to be better than the virtual cursor
- pressing buttons in UI actually presses twice (and I don't know how to fix it)
however, I think this is better than *not* having any controller support. Let me know what you think, and if you find any issues outside of those mentioned above.

**Review by lolyay270 — CHANGES_REQUESTED** [review]
## Review
Your comments well document methods and smaller code chunks, making them easy to understand and follow.

Everything works well with both xbox and playstation controllers, but an idea for the future might be deadzones.

The only issue I found is that Joystick, Touchscreen and XR (mixed reality) controls are included in the `InputSystem_Actions` file, so we should either address them in the `InputDeviceManager` script or remove them.

This feature has been implemented well to give accessibility for those who use controllers, and is a huge step towards our accessibility goals.

**Comment by otherotherjosh** [comment]
Besides dealing with other types of input being outside the scope of this branch, I don't see much of an issue with those bindings just *existing*. We can remove or implement them at a later date, but officially the game only supports keyboard and controller, so I don't (yet) care what happens when someone tries to plug in a joystick.

**Review by lolyay270 — APPROVED** [review]
I accept that the inputs can just sit and not effect the game

**Pull request merged**
